-- SUPERSEDED — do not run this file.
--
-- This was the original one-time setup script. It is no longer the schema:
-- the live schema is the sum of every file in supabase/migrations/, squashed
-- into 20260512040000_baseline.sql and extended incrementally after that.
--
-- Running it on a fresh project would produce a BROKEN database. It creates
-- public.leagues WITHOUT the client_tag column, so the baseline's
-- `create table if not exists` becomes a silent no-op and every subsequent
-- league write fails (leagues_pre_update_guard reads OLD.client_tag;
-- upsert_league_with_cas sets client_tag). It also omits pins/verify_pin
-- (login impossible), leagues_history (no audit trail, no fresh-overwrite
-- protection), leagues_snapshots, and push_subs.
--
-- To set up a fresh project:   supabase db push
-- To change the schema:        add a new file under supabase/migrations/
--
-- Kept as a stub rather than deleted so anyone following an old link or an
-- old shell-history command lands on this warning instead of a 404.
